language: php
php:
  - 5.6
  - 5.5
  - hhvm
  - 7.0

sudo: false

matrix:
  fast_finish: true

before_install:
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi;
    - pip install --user codecov

before_script:
  # Install apc
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then sh -c "mkdir -p ./travis_cache/`php-config --vernum`"; fi
  - if [[ "$TRAVIS_PHP_VERSION" == 5* ]]; then MODULES="apcu.so:20:apcu-4.0.10" ./tests/travis/modulecache.sh; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then MODULES="apcu.so:20:apcu apc.so:21:apcu_bc-beta" ./tests/travis/modulecache.sh; fi
  - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./tests/travis/php.ini; fi

  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script:
    - php -dzend_extension=xdebug.so vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - codecov
